(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*
This is the ALAS package, \[Copyright] Emilio Pisanty (2021). For the notebook that generated this package file and additional documentaion, see https://github.com/episanty/ALAS.
*)


(* ::Input::Initialization:: *)
BeginPackage["ALAS`"];


(* ::Input::Initialization:: *)
$ALASVersion::usage="$ALASVersion prints the current version of the ALAS package in use and its timestamp.";
$ALASTimestamp::usage="$ALASTimestamp prints the timestamp of the current version of the ALAS package.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
$ALASVersion:="ALAS v0.1, "<>$ALASTimestamp;


(* ::Input::Initialization:: *)
$ALASTimestamp="Tue 18 May 2021 13:16:21";
End[];


(* ::Input::Initialization:: *)
$ALASDirectory::usage="$ALASDirectory is the directory where the current ALAS package instance is located.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
With[{softLinkTestString=StringSplit[StringJoin[ReadList["! ls -la "<>StringReplace[$InputFileName,{" "->"\\ "}],String]]," -> "]},
If[Length[softLinkTestString]>1,(*Testing in case $InputFileName is a soft link to the actual directory.*)
$ALASDirectory=StringReplace[DirectoryName[softLinkTestString[[2]]],{" "->"\\ "}],
$ALASDirectory=StringReplace[DirectoryName[$InputFileName],{" "->"\\ "}];
]];
End[];


(* ::Input::Initialization:: *)
$ALASCommit::usage="$ALASCommit returns the git commit log at the location of the ALAS package if there is one.";
$ALASCommit::OS="$ALASCommit has only been tested on Linux.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
$ALASCommit:=(If[$OperatingSystem!="Unix",Message[$ALASCommit::OS]];
StringJoin[Riffle[ReadList["!cd "<>$ALASDirectory<>" && git log -1",String],{"\n"}]]);
End[];


(* ::Input::Initialization:: *)
EndPackage[];


(* ::Input::Initialization:: *)
DistributeDefinitions["ALAS`"];



